name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ docker-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Docker Action
        id: hello-action
        uses: ./docker-action
        with:
          who-to-greet: '@bensonaddo'

      - name: Get Ouput Time in Container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello!" # step.id.output.time
